apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq
spec:
  dependsOn:
    - name: rabbitmq-base
  interval: 5m
  path: "./custom/cluster.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system