apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure
  - ./rabbitmq-base/base/gitrepository.yaml
  - ./rabbitmq-base/kustomization.yaml
  - ./rabbitmq-cluster/kustomization.yaml