apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 5m
  url: https://github.com/lsc-sde/iac-flux-rabbitmq
  ref:
    branch: release/0.1.14