apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq-base
  namespace: rabbitmq
spec:
  interval: 5m
  path: "./rabbitmq-base/base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: rabbitmq
    namespace: rabbitmq
 