apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rabbitmq-base
  namespace: rabbitmq
namespace: rabbitmq
resources:
  - repository.yaml
  - release.yaml
  - namespace.yaml
 