apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq #${observability_metrics_namespace}
resources:
  - repository.yaml
  - release.yaml
  - namespace.yaml
  - rabbitmq-cluster.yaml
 