apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq #${observability_metrics_namespace}
  #annotations:
    #xlscsde.nhs.uk/flux-branch: main #${keda_branch}
spec:
  #targetNamespace: observability-metrics #${observability_metrics_namespace}
  releaseName: rabbitmq
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: "4.3.19" #${observability_metrics_chart_version}
      sourceRef:
        kind: HelmRepository
        name: rabbitmq-repo
        namespace: rabbitmq #${observability_metrics_namespace} 
  interval: 10s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true